name: Notification on push

on:
  release:
    types: [published]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Nftpixels
        DISCORD_AVATAR: https://raw.githubusercontent.com/LeGitHubDeTai/github-to-discord/main/icon.png
        MESSAGE_TITLE: New Version Released
        MESSAGE_DESCRIPTION: Find our more about our latest release!
        MESSAGE_URL: https://github.com/nftpixels/NFTEZ
        MESSAGE_COLOR: 5814783
        CONTENT: null
        MESSAGE_TITLE: "New Version"
        MESSAGE_DESCRIPTION: "Tai Studio"
        MESSAGE_URL: 'https://github.com/nftpixels/NFTEZ'
        SECTION_NAME: "ChangeLog"
        AUTHOR_NAME: "Rein"
        FOOTER_TEXT: "- Rein Weyers -"
        FOOTER_URL: "https://google.com"
        IMAGE: null;
